### ISSUE TITLE
Laverna server instalation fails - during "gulp build"

### ISSUE THREAD

**Issue by DvorakDavid** [Laverna/laverna#369]
When "build minified version of Laverna", run in the laverna folder command "gulp build".  Instalation fails - see bellow

user@pc-user:/var/www/laverna$ gulp build

/var/www/laverna/gulpfile.js:7
    return require(`./gulps/${task}`)(gulp, plugins, pkg);
                   ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)
    at /usr/lib/node_modules/gulp/node_modules/liftoff/index.js:159:9

Tested "master" and "dev" branch 
Server Ubuntu 14.04, nodejs v0.10.25

**Comment by varod** [comment]
I got a similar error. I've upgraded nodejs in v5.4.1 then it was ok.
I've used this method to upgrade node : 

```
sudo npm cache clean -f  
sudo npm install -g n  
sudo n stable  
sudo ln -sf /usr/local/n/versions/node/<VERSION>/bin/node /usr/bin/node  
```

**Comment by DvorakDavid** [comment]
to varod => Confirm - this is solution, now install OK
