### ISSUE TITLE
Linux Installation

### ISSUE THREAD

**Issue by jlpoolen** [Laverna/laverna#551]
I followed the instructions to install on Linux.

arrived at:
```
themis laverna # gulp build
(node:31867) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
module.js:442
    throw err;
    ^

Error: Cannot find module 'dev-ip'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/src/laverna/gulps/mobile.js:5:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
themis laverna #
``` 
which was remedied with:

`npm install dev-ip`

should dev-ip be included in some list of dependencies?

**Comment by wwebfor** [comment]
Yes, it should be. It was resolved with this commit https://github.com/Laverna/laverna/commit/8ae198cc52e8cee8f34bc0f0e0203f4662adb4dd
