### ISSUE TITLE
App doesn't open. Throws an exception everytime

### ISSUE THREAD

**Issue by harryi3t** [Laverna/laverna#876]
I tried downloading the latest app. That also throws an exception.
![image](https://user-images.githubusercontent.com/5207331/33221939-73e6f594-d179-11e7-8a8c-9ce0ba9e912b.png)

### Error message
```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from #<Object>
    at validateState (/private/var/folders/y7/84_s93tn1gb4pfdqwj1y7rgw0000gn/T/AppTranslocation/3BB54CF6-5E6F-4E28-82B9-E700379554AD/d/laverna.app/Contents/Resources/app/node_modules/electron-window-state/index.js:46:34)
    at module.exports (/private/var/folders/y7/84_s93tn1gb4pfdqwj1y7rgw0000gn/T/AppTranslocation/3BB54CF6-5E6F-4E28-82B9-E700379554AD/d/laverna.app/Contents/Resources/app/node_modules/electron-window-state/index.js:154:3)
    at Object.createWindow (/private/var/folders/y7/84_s93tn1gb4pfdqwj1y7rgw0000gn/T/AppTranslocation/3BB54CF6-5E6F-4E28-82B9-E700379554AD/d/laverna.app/Contents/Resources/app/electron.js:189:22)
    at Object.onReady (/private/var/folders/y7/84_s93tn1gb4pfdqwj1y7rgw0000gn/T/AppTranslocation/3BB54CF6-5E6F-4E28-82B9-E700379554AD/d/laverna.app/Contents/Resources/app/electron.js:147:10)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```

### App code that fails
```js
// electron.js#187
// Recover window state (width, height, and x&y position)
        this.state = windowStateKeeper('main', {
            width  : 1000,
            height : 600
        });
```

For the time being I have updated the code to 
```js
this.state = {x:0, y:0, width: 1000, height: 600};

// And commented out the logic to persist the state

// win.on('close', function() {
//     this.state.saveState(win);
// }.bind(appHelper));
```
Now atleast I can continue using the app.
Please, could you fix the underlying issue, so that I don't need to use this hacky solution.
Thanks, great work!

**Comment by funilrys** [comment]
@wwebfor this seems to be urgent ...

**Comment by Kusken** [comment]
I have exactly the same issue... 
The day after installed the desktop app it started throwing exceptions on startup.

**Comment by shanetuohy** [comment]
Same issue here. On Mac. I generally have been using the app in macs 'full screen' mode where it fills an entire desktop if that gives any clue as to what's going on.

**Comment by jcat12345** [comment]
Help! I'm not a programmer *at all*. I found Laverna and liked it so transferred all my notes into it, added a password and all was good for a few days. This morning when I fired up my workstation, Laverna threw an error that looks to be the same as above:
![image](https://user-images.githubusercontent.com/35699076/35231620-31c4db68-ff91-11e7-8e40-886d73191505.png)

I am on Windows 7 x64. It looks like others were smart enough to do a workaround. However as a non-programmer I don't know what to do.

Can someone help? Or at least tell me how to extract my notes -- so I can move to another tool until this gets fixed?

THANKS

**Comment by jcat12345** [comment]
Thank you very much for the help!

For any other non-programmers that chance upon this thread: You can open the electron.js file with any text editor. However life is easier if you have one like Notepad++ which shows you the line number, etc. It is free.

In case you make a mistake editing I recommend copying the file so you preserve the original. 

Once in the file if you find multiple lines to do with the "Recover window state...", comment all of them out like this:
  // Recover window state (width, height, and x&y position)
       // this.state = windowStateKeeper('main', {
       //     width  : 1000,
       //     height : 600
       //});
Then add a new line like this:
	   this.state = {x:0, y:0, width: 1000, height: 600};

Per the other contributor's comment I also went ahead and commented out the other line, like this:
  //  win.on('close', function() {
        //    this.state.saveState(win);
        //}.bind(appHelper));

I've got it running again now. Thanks so much!

**Comment by Djohn12** [comment]
I came across this error today and laverna wouldn't launch anymore, your trick worked for me on Linux 16.04 \o/

Had some hot stuff I couldn't get my hand on anymore,
you just saved my life,

thank you very much

**Comment by funilrys** [comment]
Hi there, 
if you use Arch Linux it's patched and published into the AUR package.

If you use other Linux Distribution (an no Ubuntu 16.04 is not Linux 16.04: [read more](https://www.quora.com/What-is-difference-between-Ubuntu-and-Linux?share=1)) I published the patch which fix that at https://github.com/Laverna/laverna/issues/913#issuecomment-365572643 or at https://aur.archlinux.org/cgit/aur.git/tree/913.patch?h=laverna if you prefer.

Also, please report to https://github.com/Laverna/laverna/issues/971#issuecomment-411423965 for the state of this project.
