### ISSUE TITLE
Error gulp default

### ISSUE THREAD

**Issue by KenrySanchez** [Laverna/laverna#890]
Hi guys. I recently update my dev branch and when I try to deploy laverna, it give me this error.

Error: Cannot find module 'webpack-stream'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Kenry/DEV/laverna/gulps/bundle.js:3:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

I know now there is both web-pack files configuration but I want to know if this is a bug or I just fork my branch from the master until we solve the problem with web-pack.

**Comment by KenrySanchez** [comment]
I solve it. I do `npm install` but from the master branch not from the dev. The web-pack configuration is just there. I'm going to close this issue. Thanks!!
