### ISSUE TITLE
Problems with rpm installation

### ISSUE THREAD

**Issue by eldragon87** [Laverna/laverna#899]
I am trying to install the RPM package in Fedora 27, however, the following error appears in the file

```
error: /home/ogonzalez/Descargas/buttercup-desktop-0.25.2.x86_64.rpm: signature region 62: tag number mismatch il 7 ril 6 dl 792 rdl 380

Traceback (most recent call last):
  File "/usr/bin/dnf", line 58, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 179, in user_main
    errcode = main(args)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 64, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 99, in _main
    return cli_run(cli, base)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 123, in cli_run
    ret = resolving(cli, base)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 154, in resolving
    base.do_transaction(display=displays)
  File "/usr/lib/python3.6/site-packages/dnf/cli/cli.py", line 238, in do_transaction
    super(BaseCli, self).do_transaction(display)
  File "/usr/lib/python3.6/site-packages/dnf/base.py", line 735, in do_transaction
    self.transaction._populate_rpm_ts(self._ts)
  File "/usr/lib/python3.6/site-packages/dnf/transaction.py", line 196, in _populate_rpm_ts
    hdr = tsi.installed._header
  File "/usr/lib/python3.6/site-packages/dnf/package.py", line 87, in _header
    return dnf.rpm._header(self.localPkg())
  File "/usr/lib/python3.6/site-packages/dnf/rpm/__init__.py", line 70, in _header
    return ts.hdrFromFdno(fdno)
  File "/usr/lib64/python3.6/site-packages/rpm/transaction.py", line 174, in hdrFromFdno
    raise rpm.error("error reading package header")
_rpm.error: error reading package header
```

Is it a bug? Is there a solution?

**Comment by eldragon87** [comment]
Sorry, wrong repository.
