### ISSUE TITLE
Error executing gulp build

### ISSUE THREAD

**Issue by jack9603301** [Laverna/laverna#986]
Error executing gulp build

```
[root@qhjack laverna]# gulp build
assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/www/root/laverna/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/www/root/laverna/node_modules/undertaker/lib/task.js:13:8)
    at module.exports (/www/root/laverna/gulps/mobile.js:83:10)
    at getTask (/www/root/laverna/gulpfile.js:10:38)
    at /www/root/laverna/gulpfile.js:22:19
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/www/root/laverna/gulpfile.js:21:2)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)

```

**Comment by daed** [comment]
Laverna isn't supported at this repo.  See https://github.com/Laverna/laverna/issues/971 for background information.
